# Generated by Django 5.1 on 2024-10-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelblogapp', '0003_bachelor_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bachelor_package',
            name='Numberofguest',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bachelor_package',
            name='Phonenumber',
            field=models.IntegerField(),
        ),
    ]
