# Generated by Django 5.1 on 2024-10-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelblogapp', '0004_alter_bachelor_package_numberofguest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BachelorPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Phonenumber', models.IntegerField()),
                ('Checkin', models.DateField()),
                ('Checkout', models.DateField()),
                ('Roomtype', models.CharField(max_length=100)),
                ('Numberofguest', models.IntegerField()),
                ('Specialrequest', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='bachelor_package',
        ),
    ]
