# Generated by Django 5.1 on 2024-10-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelblogapp', '0005_bachelorpackage_delete_bachelor_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='calicutbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cFullname', models.CharField(max_length=100)),
                ('cEmail', models.EmailField(max_length=100)),
                ('cPhonenumber', models.IntegerField()),
                ('cTripdate', models.DateTimeField()),
                ('cTravelers', models.IntegerField()),
                ('cSpecialrequest', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
